version: "2"

services:
  config-server:
    image: psgabriel/spring-petclinic-config-server
    container_name: config-server
    hostname: config-server
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=config-server_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    ports:
      - 8888:8888

  discovery-server:
    image: psgabriel/spring-petclinic-discovery-server
    container_name: discovery-server
    hostname: discovery-server
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=discovery-server_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://config-server:8888",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 8761:8761

  customers-service:
    image: psgabriel/spring-petclinic-customers-service
    container_name: customers-service
    hostname: customers-service
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=customers-service_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 8081:8081

  visits-service:
    image: psgabriel/spring-petclinic-visits-service
    container_name: visits-service
    hostname: visits-service
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=visits-service_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 8082:8082

  vets-service:
    image: psgabriel/spring-petclinic-vets-service
    container_name: vets-service
    hostname: vets-service
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=vets-service_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 8083:8083

  api-gateway:
    image: psgabriel/spring-petclinic-api-gateway
    container_name: api-gateway
    hostname: api-gateway
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=api-gateway_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    hostname: tracing-server
    mem_limit: 512M
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=tracing-server_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Djava.security.egd=file:/dev/./urandom
    ports:
      - 9411:9411

  admin-server:
    image: psgabriel/spring-petclinic-admin-server
    container_name: admin-server
    hostname: admin-server
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=admin-server_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 9090:9090

  hystrix-dashboard:
    image: psgabriel/spring-petclinic-hystrix-dashboard
    container_name: hystrix-dashboard
    hostname: hystrix-dashboard
    environment:
      - APPDYNAMICS_AGENT_TIER_NAME=hystrix-dashboard_pg
      - APPDYNAMICS_AGENT_APPLICATION_NAME=Petclinic_pg
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
    entrypoint:
      [
        "./dockerize",
        "-wait=tcp://discovery-server:8761",
        "-timeout=60s",
        "--",
        "java",
        "-javaagent:/agent/javaagent.jar",
        "-XX:+UnlockExperimentalVMOptions",
        "-XX:+UseCGroupMemoryLimitForHeap",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/app.jar",
      ]
    ports:
      - 7979:7979

  ## Grafana / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    hostname: grafana-server
    mem_limit: 256M
    ports:
      - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    hostname: prometheus-server
    mem_limit: 256M
    ports:
      - 9091:9090
